---
title: "Cross Validation"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(modelr)
library(mgcv)

knitr::opts_chunk$set(
    fig.width = 6, 
    fig.asp = .6, 
    out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
    ggplot2.continous.colour = "viridis", 
    ggplot2.continuous.fill = "viridis"
)
set.seed(1)
```

## Simulate data

```{r}
nonlin_df =
    tibble(
        id = 1:100, 
        x = runif(100, 0, 1), 
        y = 1 - 10 * (x - .3) ^ 2 + rnorm(100, 0, .3)
    )
```

Look at the data

```{r}
nonlin_df %>% 
    ggplot(aes(x = x, y = y)) +
    geom_point()
```
#Cross Validation --- by hand

Get training and testing datasets.
```{r}
train_df =
    sample_n(nonlin_df, size = 80)

test_df =
    anti_join(nonlin_df, train_df, by = "id")
```

Fit three models.
```{r}
linear_mod = lm(y ~ x, data = nonlin_df)
smooth_mod = gam(y ~ s(x), data = train_df)
wiggly_mod = gam(y ~ s(x, k= 30), sp = 10e-6, data = train_df)
```

Can I see what I just did...
```{r}
train_df %>% 
    add_predictions(linear_mod) %>% 
    ggplot(aes(x = x, y = y)) + 
    geom_point() +
    geom_line(aes(y = pred, color = "red"))
```
```{r}
train_df %>% 
    add_predictions(smooth_mod) %>% 
    ggplot(aes(x = x, y = y)) + 
    geom_point() +
    geom_line(aes(y = pred, color = "red"))
```

```{r}
train_df %>% 
    add_predictions(wiggly_mod) %>% 
    ggplot(aes(x = x, y = y)) + 
    geom_point() +
    geom_line(aes(y = pred, color = "red"))
```

```{r}
train_df %>% 
    gather_predictions(linear_mod, smooth_mod, wiggly_mod) %>% 
    ggplot(aes(x = x, y = y)) + 
    geom_point() +
    geom_line(aes(y = pred, color = "red")) +
    facet_grid(. ~ model)
```
Look at prediction accuracy.
# RMSE the smaller the better.
```{r}
rmse(linear_mod, test_df)
rmse(smooth_mod, test_df)
rmse(wiggly_mod, test_df)
```

## Cross Validation using `modelr`

```{r}
cv_df =
    crossv_mc(nonlin_df, 100)
```

What is happening here...

```{r}
cv_df %>% pull(train) %>% 
    .[[1]] %>% as_tibble()

cv_df %>% pull(test) %>% 
    .[[1]] %>% as_tibble()
```

```{r}
cv_df = 
    cv_df %>% 
    mutate(
        train = map(train, as_tibble), 
        test = map(test, as_tibble)
    )
```

Let's try to fit model and try to get RMSE for them.

```{r}
cv_df =
cv_df %>% 
    mutate(
        linear_mod = map(.x = train, ~lm(y ~ x, data = .x)), 
        smooth_mod = map(.x = train, ~gam(y ~ s(x), data = .x)), 
        wiggly_mod = map(.x = train, ~gam(y ~ s(x, k = 30),sp = 10e-6 , data = .x))
    ) %>% 
    mutate(
        rmse_linear = map2_dbl(.x = linear_mod, .y = test, ~rmse(model = .x, data = .y) ), 
        rmse_smooth = map2_dbl(.x = smooth_mod, .y = test, ~rmse(model = .x, data = .y) ), 
        rmse_wiggly = map2_dbl(.x = wiggly_mod, .y = test, ~rmse(model = .x, data = .y) )
    )
```

How do these results say about the model choices?

```{r}
cv_df %>% 
    select(starts_with("rmse")) %>% 
    pivot_longer(
        everything(), 
        names_to = "model", 
        values_to = "rmse", 
        names_prefix = "rmse_"
    ) %>% 
    ggplot(aes(x = model, y = rmse)) +
    geom_violin()
```
Compute average ...

```{r}
cv_df %>% 
    select(starts_with("rmse")) %>% 
    pivot_longer(
        everything(), 
        names_to = "model", 
        values_to = "rmse", 
        names_prefix = "rmse_"
    ) %>% 
   group_by(model) %>% 
    summarise(avg_rmse = mean(rmse))
```

